---
- name: Ensure rsyslog installed
  package:
    name: rsyslog
    state: present

- name: Enable rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes

- name: Enable remote logging (SIEM simulation)
  lineinfile:
    path: /etc/rsyslog.conf
    line: "*.* @@logserver:514"
